In [2]:
import numpy as np
from scipy import sparse
import pandas as pd


#file 
filename = "graph.dat"

#function to create adjacency matrix,This is updated functions in order to deal with large network.
def Adjacency_Matrix(filename):
    #reading csv file  in pandas 
    df=pd.read_csv(filename,sep=" ", comment='%',header= None,dtype=np.int32)
    
    #defining columns
    df.columns = ['node1', 'node2']
    #taking size 
    size=max(max(df.node1),max(df.node2))
    rows = df['node1']
    cols = df['node2']
    #creating ones matrix
    ones = np.ones(len(rows), np.int32)
    adjacency_matrix = sparse.csc_matrix((ones, (rows-1, cols-1)),shape=(size,size))
    adjacency_matrix=adjacency_matrix.transpose()+adjacency_matrix
    return adjacency_matrix

adjacency_M= Adjacency_Matrix(filename)
print('Adjacency Matrix is :\n',adjacency_M.todense())

Adjacency Matrix is :
 [[0 1 0 0 0 0 0 0]
 [1 0 1 1 0 0 0 0]
 [0 1 0 1 0 0 0 0]
 [0 1 1 0 1 0 0 0]
 [0 0 0 1 0 1 1 1]
 [0 0 0 0 1 0 0 1]
 [0 0 0 0 1 0 0 1]
 [0 0 0 0 1 1 1 0]]


In [3]:
def Gini_coefficient(A_matrix):
    degree_array=np.sort(A_matrix.sum(0,dtype=np.int32))
    sum_degree=degree_array.sum()
    sum_rank_degree=0
    i=1
    degree_array=np.array(degree_array)
    for degree in degree_array[0]:
        sum_rank_degree += (i*degree)
        i+=1
    sum_degree,sum_rank_degree
    g=np.divide(2*sum_rank_degree,len(degree_array[0])*sum_degree)
    g=g-(np.divide(len(degree_array[0])+1,len(degree_array[0])))
    return g
gini_Coef= Gini_coefficient(adjacency_M)
print("Gini Coefficient is :",gini_Coef)


Gini Coefficient is : 0.1875


In [4]:
#function to calculate triangle and took lot of time to figure out optimal method for large network
def Triangle_Count(A):
    
    no_of_triangle=0
    for i in range(np.shape(A)[0]):
        no_of_triangle +=(A[i,:].dot(A).dot(A[i,:].T))

    no_of_triangle=np.divide(no_of_triangle,6)
    return no_of_triangle[0,0]

num_Triangle=Triangle_Count(adjacency_M)
print("Number of triangle count are:",num_Triangle)


Number of triangle count are: 3.0


In [5]:
#Scalability test of function using gowalla network 
filename='out.loc-gowalla_edges'
#creating adjacency matrix
adjacency_M= Adjacency_Matrix(filename)

In [6]:
#calculating gini coefficient
gini_Coef= Gini_coefficient(adjacency_M)
print("Gini Coefficient for Gowalla Network is :",gini_Coef*100,'%')

Gini Coefficient for Gowalla Network is : 68.33529689546158 %


In [7]:
import timeit

start = timeit.default_timer()

num_Triangle=Triangle_Count(adjacency_M)
print("Number of triangle count are:",num_Triangle)

stop = timeit.default_timer()

print('Time taken: ', stop - start,'sec') 



Number of triangle count are: 2273138.0
Time taken:  474.70176025 sec
